### ISSUE TITLE
LTI Launch results in 404

### ISSUE THREAD

**Issue by scottbw** [e-ucm/rage-analytics#65]
LTI launch URL results in 404, e.g.:  

"http://rage.northeurope.cloudapp.azure.com:3000/api/login/launch/afront/gleaner"

... generates a 404 with content {"message":"Not Found"}

The course is associated with an activity, associated with a game.

Tested with Moodle and with test harness at http://ltiapps.net/test/tc.php

**Comment by RotaruDan** [comment]
This is because LTI plugin is desactivated by default. This has been activated in the latest release of the A2 image, but it's still in testing, or it can be found here: https://raw.githubusercontent.com/e-ucm/rage-analytics/36809018e41fe6667e3042a3896d58842fd28c66/docker-compose.yml

See response: https://github.com/e-ucm/rage-analytics/issues/64#issuecomment-431333573
