### ISSUE TITLE
Error while executing rage-analytics.sh

### ISSUE THREAD

**Issue by lalar73** [e-ucm/rage-analytics#7]
Hi Manuel,
I tried to execute the new script however I get a syntax error message.

I attach the error message. (The last lines are the relevant ones).

Regards, Raja

![screen shot error message](https://cloud.githubusercontent.com/assets/15780442/11088353/e956ea68-8861-11e5-835c-84f05734a9f1.jpg)

**Comment by manuel-freire** [comment]
The script must be run with bash (/bin/bash), and will not work with ubuntu's 'sh' (/bin/dash). 

The gnome-terminal window in your screenshot is already running bash - you would just need to execute the script as `./rage-analytics.sh launch` (or, if you are restarting analytics, `./rage-analytics.sh restart`)

**Comment by manuel-freire** [comment]
Closing issue and updating documentation

**Comment by lalar73** [comment]
Thanks. I tried running with bash, however also get a syntax error

![screen shot error message 2](https://cloud.githubusercontent.com/assets/15780442/11090557/11bd7f88-8873-11e5-9c89-c6273430abb4.jpg)

**Comment by manuel-freire** [comment]
Please re-download the script. I think you are attempting to use a corrupted version. The md5sum for the current version (output of  `md5sum rage-analytics.sh`) is `368ba16677a0fbd6e43d031bb73d5c96  rage-analytics.sh` - what is your output?

**Comment by lalar73** [comment]
I was wondering whether it was due to copy&paste in Windows vs executing in Unix. Now I've installed SourceTree and connected to rage-analytics. 

Am getting the same errors, but it's a different .sh file (See md5sum value in screen-shot). Please email me the script.

![screen shot error message 2](https://cloud.githubusercontent.com/assets/15780442/11091268/15dce076-8879-11e5-8d8b-d3a7f21bf59c.jpg)

**Comment by manuel-freire** [comment]
Hmm, copy&paste in windows is a likely suspect. How do you copy&paste a text file from windows to linux? By opening the text in a program and then pasting it again? If that program does not preserve unix linebreaks, that may be the problem. Also, it seems clear that you are trying to execute a different script from the one in the repository.

I propose the following procedure, since your VM seems to have Ubuntu in it:
1. `sudo apt-get install git` - this will install git in the VM
2. `git clone https://github.com/e-ucm/rage-analytics.git` - this create a binary-equals copy of the repository
3. `cd rage-analytics` - this lands you in the recently checked-out copy
4. `./rage-analytics.sh launch` - installs everything, using a clean script

Mailing the script makes no sense - you can download it fine from [this repository's copy](https://raw.githubusercontent.com/e-ucm/rage-analytics/master/rage-analytics.sh)

**Comment by lalar73** [comment]
I thought so too due to the \r in the error statements. 

I have a Windows laptop and therefore installed Virtual Box and am running Ubuntu on a VM. Sharing a folder between the filesystems using the media folder. Intially I was just opening in a sublime editor and copy-pasting. This afternoon I installed Source-Tree and got the original rage-analytics.sh file which still gave other errors.

Anyways, I now followed the instructions in your last message and now much further :-) Thanks!

There are some docker messages from the running the  rage-analytics.sh script
![screenshot from 2015-11-11 16-36-57](https://cloud.githubusercontent.com/assets/15780442/11095049/7cadd5ca-8893-11e5-813d-9e76627c4155.png)

**Comment by manuel-freire** [comment]
You do not need to send screenshots - the information is in the text, and you should be able to copy and paste it (see http://askubuntu.com/a/73067).

In your case, it seems that docker installation is failing, due to a network issue (a server that was supposed to provide keys used to sign docker binaries was unreachable). This seems to be documented in the [docker installation section](http://docs.docker.com/v1.8/installation/ubuntulinux/) - apparently the fix is to install the keys manually:

```
Note: If your company is behind a filtering proxy, you may find that the apt-key command 
fails for the Docker repo during installation. To work around this, add the key directly using 
the following:
```

`curl -sSL https://get.docker.com/gpg | sudo apt-key add -`

**Comment by manuel-freire** [comment]
Can you test with the latest version? I am marking this issue as closed.
